version: '3'

services:
  api-registro-accesos:
    build:
      context: ./api/registro-accesos
      dockerfile: Dockerfile
    container_name: api-registro-accesos
    ports:
      - "5001:3000"
    volumes:
      - ./api/registro-accesos/src:/app